#!/bin/bash

echo "Docker build started..."

DATA_DIR=`mktemp -d`
REPO_DIR=`pwd`
REPO_NAME=`basename $REPO_DIR .git`
BRANCH_NAME=`basename $1`
TAG_NAME=$REPO_NAME:$BRANCH_NAME

FILES=`find $GL_ADMIN_BASE -name docker-compose.yml | \
	xargs grep -l -r $TAG_NAME`

git clone $REPO_DIR -b $BRANCH_NAME $DATA_DIR
rm $DATA_DIR/.git -rf

# Find Dockerfile
if [ ! -f $DATA_DIR/Dockerfile ]; then
	while read line
	do
		if [ -f `dirname $line`/$REPO_NAME.Dockerfile ]; then
			cp `dirname $line`/$REPO_NAME.Dockerfile $DATA_DIR/Dockerfile
			break
		fi
	done <<<"$FILES"
fi

# Build image
if [ -f $DATA_DIR/Dockerfile ]; then
	sudo docker build -t $TAG_NAME $DATA_DIR
fi

# Restart services
if [ -f $DATA_DIR/docker-compose.yml ]; then
  sudo bash -c "cd `dirname $DATA_DIR` && docker-compose up -d"
fi

rm $DATA_DIR -rf

while read line
do
  sudo bash -c "cd `dirname $line` && docker-compose up -d"
done <<<"$FILES"
